const trouser=[
    {
         img: "https://m.media-amazon.com/images/I/61SDBt9UtaL._SY741_.jpg",
    desc: "Men's Regular Fit Casual Trouser",
    price: "₹649",
    discount: "941",
    MRP: "1590",
    SIZE: X,
    M,
    L,
    XL,
    XXl,
    },
     {
         img: "https://m.media-amazon.com/images/I/61SDBt9UtaL._SY741_.jpg",
    desc: "Men's Regular Fit Casual Trouser",
    price: "₹649",
    discount: "941",
    MRP: "1590",
    SIZE: X,
    M,
    L,
    XL,
    XXl,
    },
]