const Mencollection = [
  // Formal Shirts
  {
    id: "formalshirt-1",
    img: "https://www.hancockfashion.com/cdn/shop/files/5579BGREEN_1_M.jpg?v=1734411915&width=1800",
    name: "Bottle Green Formal Shirt",
    desc: "Men Bottle Green Solid Pure Cotton Slim Fit Formal Shirt",
    price: "1100",
    discount: "52% off", // Calculated: (2299 - 1100) / 2299 * 100
    MRP: "2299",
    category: "Formal Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "formalshirt-2",
    img: "https://www.hancockfashion.com/cdn/shop/files/5579BGREEN_1_M.jpg?v=1734411915&width=1800",
    name: "Bottle Green Formal Shirt",
    desc: "Men Bottle Green Solid Pure Cotton Slim Fit Formal Shirt",
    price: "1100",
    discount: "52% off",
    MRP: "2299",
    category: "Formal Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "formalshirt-3",
    img: "https://www.hancockfashion.com/cdn/shop/files/5579BGREEN_1_M.jpg?v=1734411915&width=1800",
    name: "Bottle Green Formal Shirt",
    desc: "Men Bottle Green Solid Pure Cotton Slim Fit Formal Shirt",
    price: "1100",
    discount: "52% off",
    MRP: "2299",
    category: "Formal Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "formalshirt-4",
    img: "https://www.hancockfashion.com/cdn/shop/files/5579BGREEN_1_M.jpg?v=1734411915&width=1800",
    name: "Bottle Green Formal Shirt",
    desc: "Men Bottle Green Solid Pure Cotton Slim Fit Formal Shirt",
    price: "1100",
    discount: "52% off",
    MRP: "2299",
    category: "Formal Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "formalshirt-5",
    img: "https://www.hancockfashion.com/cdn/shop/files/5579BGREEN_1_M.jpg?v=1734411915&width=1800",
    name: "Bottle Green Formal Shirt",
    desc: "Men Bottle Green Solid Pure Cotton Slim Fit Formal Shirt",
    price: "1100",
    discount: "52% off",
    MRP: "2299",
    category: "Formal Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  // Formal Pants
  {
    id: "formalpants-1",
    img: "https://pantproject.com/cdn/shop/files/DSC1113.jpg?v=1743609636",
    name: "Grey Formal Pants",
    desc: "Effortless Grey Slim Fit Stretch Formal Pants",
    price: "1099",
    discount: "45% off", // Calculated: (1999 - 1099) / 1999 * 100
    MRP: "1999",
    category: "Formal Pants",
    sizes: ["XS", "M", "L", "XL", "XXL"],
  },
  {
    id: "formalpants-2",
    img: "https://pantproject.com/cdn/shop/files/DSC1113.jpg?v=1743609636",
    name: "Grey Formal Pants",
    desc: "Effortless Grey Slim Fit Stretch Formal Pants",
    price: "1099",
    discount: "45% off",
    MRP: "1999",
    category: "Formal Pants",
    sizes: ["XS", "M", "L", "XL", "XXL"],
  },
  // Oversized T-Shirts
  {
    id: "oversizedtshirt-1",
    img: "https://assets.ajio.com/medias/sys_master/root/20230629/dXmR/649cf777a9b42d15c920e9fe/-473Wx593H-466083850-white-MODEL.jpg",
    name: "Typographic Oversized T-Shirt",
    desc: "Typographic Print Oversized T-Shirt",
    price: "504",
    discount: "58% off", // Calculated: (1199 - 504) / 1199 * 100
    MRP: "1199",
    category: "Oversized T-Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "oversizedtshirt-2",
    img: "https://assets.ajio.com/medias/sys_master/root/20230629/dXmR/649cf777a9b42d15c920e9fe/-473Wx593H-466083850-white-MODEL.jpg",
    name: "Typographic Oversized T-Shirt",
    desc: "Typographic Print Oversized T-Shirt",
    price: "504",
    discount: "58% off",
    MRP: "1199",
    category: "Oversized T-Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  // Check Shirts
  {
    id: "checkshirt-1",
    img: "https://bananaclub.co.in/cdn/shop/files/DobbySteelGreyCheckShirt_6.jpg?v=1738823344&width=800",
    name: "Steel Grey Check Shirt",
    desc: "Dobby Steel Grey Check Shirt",
    price: "1049",
    discount: "16% off", // Calculated: (1248 - 1049) / 1248 * 100
    MRP: "1248",
    category: "Check Shirt",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "checkshirt-2",
    img: "https://bananaclub.co.in/cdn/shop/files/DobbySteelGreyCheckShirt_6.jpg?v=1738823344&width=800",
    name: "Steel Grey Check Shirt",
    desc: "Dobby Steel Grey Check Shirt",
    price: "1049",
    discount: "16% off",
    MRP: "1248",
    category: "Check Shirt",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "checkshirt-3",
    img: "https://bananaclub.co.in/cdn/shop/files/DobbySteelGreyCheckShirt_6.jpg?v=1738823344&width=800",
    name: "Steel Grey Check Shirt",
    desc: "Dobby Steel Grey Check Shirt",
    price: "1049",
    discount: "16% off",
    MRP: "1248",
    category: "Check Shirt",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "checkshirt-4",
    img: "https://bananaclub.co.in/cdn/shop/files/DobbySteelGreyCheckShirt_6.jpg?v=1738823344&width=800",
    name: "Steel Grey Check Shirt",
    desc: "Dobby Steel Grey Check Shirt",
    price: "1049",
    discount: "16% off",
    MRP: "1248",
    category: "Check Shirt",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  // Oversized Shirts
  {
    id: "oversizedshirt-1",
    img: "https://www.gritstones.com/cdn/shop/files/GSHS-1O-15-BLK.jpg?v=1716400414&width=1800",
    name: "Black Oversized Shirt",
    desc: "Black Oversized Self Design Shirt",
    price: "799",
    discount: "50% off", // Calculated: (1599 - 799) / 1599 * 100
    MRP: "1599",
    category: "Oversized Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "oversizedshirt-2",
    img: "https://www.gritstones.com/cdn/shop/files/GSHS-1O-15-BLK.jpg?v=1716400414&width=1800",
    name: "Black Oversized Shirt",
    desc: "Black Oversized Self Design Shirt",
    price: "799",
    discount: "50% off",
    MRP: "1599",
    category: "Oversized Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "oversizedshirt-3",
    img: "https://www.gritstones.com/cdn/shop/files/GSHS-1O-15-BLK.jpg?v=1716400414&width=1800",
    name: "Black Oversized Shirt",
    desc: "Black Oversized Self Design Shirt",
    price: "799",
    discount: "50% off",
    MRP: "1599",
    category: "Oversized Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "oversizedshirt-4",
    img: "https://www.gritstones.com/cdn/shop/files/GSHS-1O-15-BLK.jpg?v=1716400414&width=1800",
    name: "Black Oversized Shirt",
    desc: "Black Oversized Self Design Shirt",
    price: "799",
    discount: "50% off",
    MRP: "1599",
    category: "Oversized Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  // Baggy Jeans
  {
    id: "baggyjeans-1",
    img: "https://offduty.in/cdn/shop/products/ff2def08-93ae-4984-89e8-8352dea110da_1800x1800.jpg?v=1676893036",
    name: "Blue Baggy Jeans",
    desc: "Blue Stone Wash Baggy Fit Cargo Men Jeans",
    price: "1200",
    discount: "29% off", // Calculated: (1700 - 1200) / 1700 * 100
    MRP: "1700",
    category: "Baggy Jeans",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "baggyjeans-2",
    img: "https://offduty.in/cdn/shop/products/ff2def08-93ae-4984-89e8-8352dea110da_1800x1800.jpg?v=1676893036",
    name: "Blue Baggy Jeans",
    desc: "Blue Stone Wash Baggy Fit Cargo Men Jeans",
    price: "1200",
    discount: "29% off",
    MRP: "1700",
    category: "Baggy Jeans",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  // T-Shirts
  {
    id: "tshirt-1",
    img: "https://nobero.com/cdn/shop/files/og.jpg?v=1744007258",
    name: "Classic T-Shirt",
    desc: "Plain Classic Fit T-Shirt",
    price: "499",
    discount: "50% off", // Calculated: (999 - 499) / 999 * 100
    MRP: "999",
    category: "T-Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "tshirt-2",
    img: "https://myfinch.in/cdn/shop/files/4H9A8371.jpg?v=1738214024&width=1946",
    name: "Classic T-Shirt",
    desc: "Plain Classic Fit T-Shirt",
    price: "699",
    discount: "30% off", // Calculated: (999 - 699) / 999 * 100
    MRP: "999",
    category: "T-Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "tshirt-3",
    img: "https://myfinch.in/cdn/shop/files/4H9A8371.jpg?v=1738214024&width=1946",
    name: "Classic T-Shirt",
    desc: "Plain Classic Fit T-Shirt",
    price: "699",
    discount: "30% off",
    MRP: "999",
    category: "T-Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "tshirt-4",
    img: "https://myfinch.in/cdn/shop/files/4H9A8371.jpg?v=1738214024&width=1946",
    name: "Classic T-Shirt",
    desc: "Plain Classic Fit T-Shirt",
    price: "699",
    discount: "30% off",
    MRP: "999",
    category: "T-Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "tshirt-5",
    img: "https://myfinch.in/cdn/shop/files/4H9A8371.jpg?v=1738214024&width=1946",
    name: "Classic T-Shirt",
    desc: "Plain Classic Fit T-Shirt",
    price: "699",
    discount: "30% off",
    MRP: "999",
    category: "T-Shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
];



export default Object.freeze(Mencollection); // Freeze for stability